# Generated by Django 6.0.4 on 2026-04-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_attendancesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
